--Alter judicial_user_profile
ALTER TABLE judicial_user_profile DROP COLUMN is_judge;
ALTER TABLE judicial_user_profile DROP COLUMN is_panel_member;
ALTER TABLE judicial_user_profile DROP COLUMN is_magistrate;
ALTER TABLE judicial_user_profile DROP COLUMN mrd_created_time;
ALTER TABLE judicial_user_profile DROP COLUMN mrd_updated_time;
ALTER TABLE judicial_user_profile DROP COLUMN mrd_deleted_time;
--Alter judicial_office_appointment
ALTER TABLE judicial_office_appointment DROP COLUMN primary_location;
ALTER TABLE judicial_office_appointment DROP COLUMN secondary_location;
ALTER TABLE judicial_office_appointment DROP COLUMN tertiary_location;
ALTER TABLE judicial_office_appointment DROP COLUMN mrd_created_time;
ALTER TABLE judicial_office_appointment DROP COLUMN mrd_updated_time;
ALTER TABLE judicial_office_appointment DROP COLUMN mrd_deleted_time;
--Alter judicial_office_authorisation
ALTER TABLE judicial_office_authorisation DROP COLUMN mrd_created_time;
ALTER TABLE judicial_office_authorisation DROP COLUMN mrd_updated_time;
ALTER TABLE judicial_office_authorisation DROP COLUMN mrd_deleted_time;
--Alter judicial_role_type
ALTER TABLE  judicial_role_type DROP COLUMN mrd_created_time;
ALTER TABLE  judicial_role_type DROP COLUMN mrd_updated_time;
ALTER TABLE  judicial_role_type DROP COLUMN mrd_deleted_time;
--Alter judicial_location_mapping
ALTER TABLE judicial_location_mapping DROP COLUMN mrd_created_time;
ALTER TABLE judicial_location_mapping DROP COLUMN mrd_updated_time;
ALTER TABLE judicial_location_mapping DROP COLUMN mrd_deleted_time;
--Alter judicial_service_code_mapping
ALTER TABLE judicial_service_code_mapping DROP COLUMN mrd_created_time;
ALTER TABLE judicial_service_code_mapping DROP COLUMN mrd_updated_time;
ALTER TABLE judicial_service_code_mapping DROP COLUMN mrd_deleted_time;
--Alter judicial_ticket_code_mapping
ALTER TABLE judicial_ticket_code_mapping DROP COLUMN mrd_created_time;
ALTER TABLE judicial_ticket_code_mapping DROP COLUMN mrd_updated_time;
ALTER TABLE judicial_ticket_code_mapping DROP COLUMN mrd_deleted_time;
--Alter base_location_type
ALTER TABLE base_location_type DROP COLUMN mrd_created_time;
ALTER TABLE base_location_type DROP COLUMN mrd_updated_time;
ALTER TABLE base_location_type DROP COLUMN mrd_deleted_time;
--Alter region_type
ALTER TABLE region_type DROP COLUMN mrd_created_time;
ALTER TABLE region_type DROP COLUMN mrd_updated_time;
ALTER TABLE region_type DROP COLUMN mrd_deleted_time;
--Alter jrd_lrd_region_mapping
ALTER TABLE jrd_lrd_region_mapping DROP COLUMN mrd_created_time;
ALTER TABLE jrd_lrd_region_mapping DROP COLUMN mrd_updated_time;
ALTER TABLE jrd_lrd_region_mapping DROP COLUMN mrd_deleted_time;

DELETE FROM judicial_service_code_mapping WHERE service_id in ('21','55');
DELETE FROM judicial_ticket_code_mapping WHERE ticket_code in ('363','376');

DELETE FROM jrd_lrd_region_mapping WHERE jrd_region_id in ('29','30','31','34');

truncate table  judicial_location_mapping  cascade;

INSERT INTO judicial_location_mapping (epimms_id,judicial_base_location_id,building_location_name,base_location_name,service_code) VALUES
('29096','754','HARROW CROWN COURT','Harrow Crown Court',NULL),
('425094','893','LEICESTER CROWN COURT','Leicester Crown Court',NULL),
('','1030','','Immigration and Asylum First Tier','BFA1'),
('','1032','','Social Entitlement','BBA3'),
('20262','747','ROYAL COURTS OF JUSTICE','Royal Courts of Justice - High Court - Chancery',NULL),
('20262','748','ROYAL COURTS OF JUSTICE','Royal Courts of Justice - High Court - Family',NULL),
('20262','749','ROYAL COURTS OF JUSTICE','Royal Courts of Justice - High Court - QB',NULL),
('20262','750','ROYAL COURTS OF JUSTICE','Royal Courts of Justice - Court of Appeal',NULL),
('312962','752','CENTRAL CRIMINAL COURT','Central Criminal Court',NULL),
('407494','753','CROYDON COUNTY COURT AND FAMILY COURT','Croydon Crown Court',NULL),
('337856','755','INNER LONDON CROWN COURT','Inner London Crown Court',NULL),
('718075','756','ISLEWORTH CROWN COURT','Isleworth Crown Court',NULL),
('699560','757','KINGSTON UPON THAMES CROWN COURT','Kingston Upon Thames Crown Court',NULL),
('127994','758','SNARESBROOK CROWN COURT','Snaresbrook Crown Court',NULL),
('337959','759','SOUTHWARK CROWN COURT','Southwark Crown Court',NULL),
('403689','760','WOOD GREEN CROWN COURT','Wood Green Crown Court',NULL),
('353988','761','WOOLWICH CROWN COURT','Woolwich Crown Court',NULL),
('229786','762','BARNET CIVIL AND FAMILY COURTS CENTRE','Barnet County Court ',NULL),
('36791','764','BRENTFORD COUNTY COURT AND FAMILY COURT','Brentford County Court ',NULL),
('29656','765','BROMLEY COUNTY COURT AND FAMILY COURT','Bromley County Court ',NULL),
('356855','766','CENTRAL FAMILY COURT (First Avenue House)','Central Family Court',NULL),
('20262','767','ROYAL COURTS OF JUSTICE','Central London County Court ',NULL),
('739514','769','CLERKENWELL AND SHOREDITCH COUNTY COURT AND FAMILY COURT','Clerkenwell and Shoreditch County Court',NULL),
('407494','770','CROYDON COUNTY COURT AND FAMILY COURT','Croydon County Court',NULL),
('898213','771','EAST LONDON FAMILY COURT','East London Family Court',NULL),
('25463','772','EDMONTON COUNTY COURT AND FAMILY COURT','Edmonton County Court',NULL),
('13660','773','KINGSTON UPON THAMES COUNTY COURT AND FAMILY COURT','Kingston Upon Thames County Court ',NULL),
('674229','775','Mayor''s and City of London Court','Major& City County Court',NULL),
('400947','776','ROMFORD COUNTY COURT AND FAMILY COURT','Romford County Court',NULL),
('621184','777','UXBRIDGE COUNTY COURT AND FAMILY COURT','Uxbridge County Court',NULL),
('268374','778','WANDSWORTH COUNTY COURT AND FAMILY COURT','Wandsworth County Court',NULL),
('373584','780','WEST LONDON FAMILY COURT','West London Family Court',NULL),
('228015','781','WILLESDEN COUNTY COURT AND FAMILY COURT','Willesden County Court',NULL),
('817181','783','AYLESBURY CROWN COURT','Aylesbury Crown Court',NULL),
('694840','784','BASILDON COMBINED COURT','Basildon Crown Court',NULL),
('507931','785','CAMBRIDGE CROWN COURT','Cambridge Crown Court',NULL),
('259679','786','CANTERBURY COMBINED COURT CENTRE','Canterbury Crown Court',NULL),
('428073','787','CHELMSFORD CROWN COURT','Chelmsford Crown Court',NULL),
('468679','789','GUILDFORD CROWN COURT','Guildford Crown Court',NULL),
('357989','790','IPSWICH CROWN COURT','Ipswich Crown Court',NULL),
('101183','791','LEWES COMBINED COURT CENTRE','Lewes Crown Court',NULL),
('486853','792','LUTON CROWN COURT','Luton Crown Court',NULL),
('465872','793','MAIDSTONE COMBINED COURT CENTRE','Maidstone Crown Court',NULL),
('471332','794','NORWICH COMBINED COURT CENTRE','Norwich Crown Court',NULL),
('371016','795','OXFORD COMBINED COURT CENTRE','Oxford Crown Court',NULL),
('471569','796','PETERBOROUGH COMBINED COURT CENTRE','Peterborough Crown Court',NULL),
('256379','797','READING CROWN COURT','Reading Crown Court',NULL),
('198303','798','ST ALBANS CROWN COURT','St Albans Crown Court',NULL),
('694840','802','BASILDON COMBINED COURT','Basildon County Court',NULL),
('446255','803','BEDFORD COUNTY COURT AND FAMILY COURT','Bedford County Court',NULL),
('478896','804','BRIGHTON COUNTY AND FAMILY COURT','Brighton County Court',NULL),
('298390','805','BRIGHTON HEARING CENTRE','Brighton Family Centre',NULL),
('257431','806','BURY ST EDMUNDS COUNTY COURT AND FAMILY COURT','Bury St Edmunds County Court',NULL),
('650344','807','CAMBRIDGE COUNTY COURT AND FAMILY COURT','Cambridge County Court',NULL),
('259679','808','CANTERBURY COMBINED COURT CENTRE','Canterbury County Court',NULL),
('816875','809','CHELMSFORD COUNTY AND FAMILY COURT','Chelmsford County Court',NULL),
('194172','812','DARTFORD COUNTY COURT AND FAMILY COURT','Dartford County Court',NULL),
('609320','814','GREAT YARMOUTH MAGISTRATES COURT AND FAMILY COURT','Great Yarmouth Family Court',NULL),
('568484','815','GUILDFORD MAGISTRATES COURT AND FAMILY COURT','Guildford County Court',NULL),
('784691','816','HASTINGS MAGISTRATES COURT','Hastings County Court',NULL),
('256913','817','HERTFORD COUNTY COURT AND FAMILY COURT','Hertford County Court',NULL),
('437303','818','HIGH WYCOMBE MAGISTRATES COURT AND FAMILY COURT','High Wycombe County Court',NULL),
('317442','819','HORSHAM COUNTY COURT AND FAMILY COURT','Horsham County Court',NULL),
('471349','820','IPSWICH COUNTY COURT AND FAMILY HEARING CENTRE','Ipswich County Court',NULL),
('101183','822','LEWES COMBINED COURT CENTRE','Lewes County Court',NULL),
('259134','825','Luton Justice Centre ','Luton County Court',NULL),
('465872','826','MAIDSTONE COMBINED COURT CENTRE','Maidstone County Court',NULL),
('487294','827','MEDWAY COUNTY COURT AND FAMILY COURT','Medway County Court',NULL),
('815997','828','MILTON KEYNES COUNTY COURT AND FAMILY COURT','Milton Keynes County Court',NULL),
('471332','829','NORWICH COMBINED COURT CENTRE','Norwich County Court',NULL),
('371016','830','OXFORD COMBINED COURT CENTRE','Oxford County Court',NULL),
('471569','831','PETERBOROUGH COMBINED COURT CENTRE','Peterborough County Court',NULL),
('185657','832','READING COUNTY COURT AND FAMILY COURT','Reading County Court',NULL),
('224403','834','SLOUGH COUNTY COURT AND FAMILY COURT','Slough County Court',NULL),
('781139','835','SOUTHEND COMBINED - CROWN, MAGS, COUNTY AND FAMILY COURTS','Southend County Court',NULL),
('298828','836','STAINES MAGISTRATES COURT AND FAMILY COURT','Staines County Court',NULL),
('659591','838','MARGATE MAGISTRATES COURT','Thanet County Court',NULL),
('403751','840','WATFORD COUNTY COURT AND FAMILY COURT','Watford County Court',NULL),
('493880','841','WORTHING MAGISTRATES AND COUNTY COURT','Worthing County Court',NULL),
('411234','842','BATH MAGISTRATES, COUNTY AND FAMILY COURT','Bath County Court',NULL),
('819890','843','BRISTOL CIVIL AND FAMILY JUSTICE CENTRE','Bristol County Court',NULL),
('477819','844','BRISTOL CROWN COURT','Bristol Crown Court',NULL),
('198592','845','GLOUCESTER AND CHELTENHAM COUNTY  AND FAMILY COURT','Gloucester and Cheltenham County Court',NULL),
('100539','846','GLOUCESTER CROWN COURT','Gloucester Crown Court',NULL),
('382409','847','TAUNTON CROWN, COUNTY AND FAMILY COURT','Taunton County Court',NULL),
('382409','848','TAUNTON CROWN, COUNTY AND FAMILY COURT','Taunton Crown Court',NULL),
('545334','849','NORTH SOMERSET MAGISTRATES','Weston-super-Mare County Court',NULL),
('315404','850','YEOVIL COUNTY, FAMILY AND MAGISTRATES COURT','Yeovil County Court',NULL),
('774335','851','BARNSTAPLE MAGISTRATES, COUNTY AND FAMILY COURT','Barnstaple County Court',NULL),
('271813','853','BODMIN COUNTY COURT AND FAMILY COURT','Bodmin County Court',NULL),
('101633','854','BOURNEMOUTH COMBINED COURT','Bournemouth Combined Court- Crown',NULL),
('101633','855','BOURNEMOUTH COMBINED COURT','Bournemouth Combined Court- County',NULL),
('624161','856','WEYMOUTH COMBINED COURT','Weymouth and Dorchester Combined Court - County',NULL),
('624161','858','WEYMOUTH COMBINED COURT','Weymouth and Dorchester Combined Court - Family',NULL),
('735217','859','EXETER COMBINED COURT','Exeter Combined Court - Crown',NULL),
('735217','860','EXETER COMBINED COURT','Exeter Combined Court - County',NULL),
('339463','861','PLYMOUTH COMBINED COURT','Plymouth Combined Court - Crown',NULL),
('339463','862','PLYMOUTH COMBINED COURT','Plymouth Combined Court - County',NULL),
('235617','863','TORQUAY AND NEWTON ABBOT COUNTY COURT AND FAMILY COURT','Torquay and Newton Abbot County Court ',NULL),
('475776','864','TRURO COMBINED COURT','Truro Combined Court - Crown',NULL),
('475776','865','TRURO COMBINED COURT','Truro Combined Court - County',NULL),
('457273','867','BASINGSTOKE COUNTY COURT AND FAMILY COURT','Basingstoke Family Court',NULL),
('457273','868','BASINGSTOKE COUNTY COURT AND FAMILY COURT','Basingstoke County Court',NULL),
('416742','871','ISLE OF WIGHT COMBINED COURT','Newport IOW Combined Court - Crown',NULL),
('416742','872','ISLE OF WIGHT COMBINED COURT','Newport IOW Combined Court - County',NULL),
('460592','873','PORTSMOUTH COMBINED COURT CENTRE','Portsmouth Combined Court - Crown',NULL),
('460592','874','PORTSMOUTH COMBINED COURT CENTRE','Portsmouth Combined Court - County',NULL),
('817113','875','SALISBURY LAW COURTS','Salisbury Combined Court - Crown',NULL),
('817113','876','SALISBURY LAW COURTS','Salisbury Combined Court - County',NULL),
('43104','877','SOUTHAMPTON COMBINED COURT CENTRE','Southampton Combined Court - Crown',NULL),
('43104','878','SOUTHAMPTON COMBINED COURT CENTRE','Southampton Combined Court - County',NULL),
('438850','879','SWINDON COMBINED COURT','Swindon Combined Court - Crown',NULL),
('438850','880','SWINDON COMBINED COURT','Swindon Combined Court - County',NULL),
('886493','881','WINCHESTER COMBINED COURT CENTRE','Winchester Combined Court - Crown',NULL),
('886493','882','WINCHESTER COMBINED COURT CENTRE','Winchester Combined Court - County',NULL),
('652852','884','CHESTERFIELD MAGISTRATES','Chesterfield County Court',NULL),
('201339','885','DERBY COMBINED COURT CENTRE','Derby Combined Court - County ',NULL),
('201339','886','DERBY COMBINED COURT CENTRE','Derby Combined Court - Crown',NULL),
('455368','887','MANSFIELD MAGISTRATES AND COUNTY COURT','Mansfield County Court',NULL),
('424213','888','NOTTINGHAM COUNTY COURT AND FAMILY COURT','Nottingham County Court',NULL),
('424213','889','NOTTINGHAM COUNTY COURT AND FAMILY COURT','Nottingham Crown Court',NULL),
('117667','890','BOSTON COUNTY COURT AND FAMILY COURT','Boston County Court',NULL),
('223503','892','LEICESTER COUNTY COURT','Leicester County Court',NULL),
('195465','894','LINCOLN COUNTY COURT AND FAMILY COURT','Lincoln County Court',NULL),
('318389','895','LINCOLN CROWN COURT','Lincoln Crown Court',NULL),
('195489','896','NORTHAMPTON CROWN COURT, COUNTY COURT AND FAMILY COURT','Northampton Combined Court - Crown',NULL),
('195489','897','NORTHAMPTON CROWN COURT, COUNTY COURT AND FAMILY COURT','Northampton Combined Court - County',NULL),
('228883','898','HEREFORD MAGISTRATES COURT','Hereford County Court',NULL),
('259170','899','SHREWSBURY JUSTICE CENTRE','Shrewsbury Crown Court',NULL),
('195472','900','STAFFORD COMBINED COURT CENTRE','Stafford Combined Court - Crown',NULL),
('195472','901','STAFFORD COMBINED COURT CENTRE','Stafford Combined Court - County',NULL),
('195496','902','STOKE-ON-TRENT COMBINED COURT','Stoke on Trent Combined Court - County',NULL),
('195496','903','STOKE-ON-TRENT COMBINED COURT','Stoke on Trent Combined Court - Crown',NULL),
('292771','904','TELFORD MAGISTRATES COURT','Telford County Court',NULL),
('102050','905','WORCESTER COMBINED COURT','Worcester Combined Court - Crown',NULL),
('102050','906','WORCESTER COMBINED COURT','Worcester Combined Court - County',NULL),
('482914','907','BIRMINGHAM CROWN COURT','Birmingham Crown Court',NULL),
('231596','908','BIRMINGHAM CIVIL AND FAMILY JUSTICE CENTRE','Birmingham Civil & Family Justice Centre - Family',NULL),
('231596','909','BIRMINGHAM CIVIL AND FAMILY JUSTICE CENTRE','Birmingham Civil & Family Justice Centre - County',NULL),
('497679','910','COVENTRY COMBINED COURT CENTRE','Coventry Combined Court - Crown',NULL),
('497679','911','COVENTRY COMBINED COURT CENTRE','Coventry Combined Court - County',NULL),
('758998','912','DUDLEY MAGISTRATES COURT','Dudley County Court',NULL),
('329990','913','NUNEATON MAGISTRATES'' COURT','Nuneaton County Court',NULL),
('177463','914','WALSALL COUNTY AND FAMILY COURT','Walsall County Court',NULL),
('736719','915','LEAMINGTON SPA MAGISTRATES'' COURT','Warwick Combined Court - Crown',NULL),
('41047','917','WOLVERHAMPTON COMBINED COURT CENTRE','Wolverhampton Combined Court - Crown',NULL),
('41047','918','WOLVERHAMPTON COMBINED COURT CENTRE','Wolverhampton Combined Court - County',NULL),
('574546','919','BARNSLEY LAW COURTS','Barnsley County Court',NULL),
('88516','920','BRADFORD COMBINED COURT CENTRE','Bradford Combined Court - Crown',NULL),
('88516','921','BRADFORD COMBINED COURT CENTRE','Bradford Combined Court - County',NULL),
('288691','922','DARLINGTON COUNTY COURT AND FAMILY COURT','Darlington County Court',NULL),
('45900','925','DONCASTER JUSTICE CENTRE SOUTH','Doncaster Crown Court',NULL),
('491107','926','DURHAM JUSTICE CENTRE','Durham County Court',NULL),
('386393','928','DURHAM CROWN COURT','Durham Crown Court',NULL),
('427519','929','GATESHEAD MAGISTRATES COURT AND FAMILY COURT','Gateshead County Court',NULL),
('478126','930','GREAT GRIMSBY COMBINED COURT CENTRE','Great Grimsby Combined Court - Crown',NULL),
('478126','931','GREAT GRIMSBY COMBINED COURT CENTRE','Great Grimsby Combined Court - County',NULL),
('505683','933','HARROGATE JUSTICE CENTRE','Harrogate County Court',NULL),
('197852','935','HUDDERSFIELD COUNTY COURT AND FAMILY COURT','Huddersfield County Court',NULL),
('195520','936','KINGSTON-UPON-HULL COMBINED COURT CENTRE','Kingston Upon Hull Combined Court - Crown',NULL),
('195520','937','KINGSTON-UPON-HULL COMBINED COURT CENTRE','Kingston Upon Hull Combined Court - County',NULL),
('455174','938','LEEDS COMBINED COURT CENTRE','Leeds Combined Court - Crown',NULL),
('455174','939','LEEDS COMBINED COURT CENTRE','Leeds Combined Court - County',NULL),
('659436','943','NEWTON AYCLIFFE MAGISTRATES COURT AND FAMILY COURT','Newton Aycliffe Family Court',NULL),
('562808','945','NORTH SHIELDS COUNTY COURT AND FAMILY COURT','North Shields County Court',NULL),
('744412','947','SCARBOROUGH JUSTICE CENTRE','Scarborough County Court',NULL),
('232607','949','SHEFFIELD COMBINED COURT CENTRE','Sheffield Combined Court - Crown',NULL),
('232607','950','SHEFFIELD COMBINED COURT CENTRE','Sheffield Combined Court - County',NULL),
('318324','951','SKIPTON MAGISTRATES AND COUNTY COURT','Skipton County Court',NULL),
('563156','952','SOUTH TYNESIDE MAGISTRATES COURT AND FAMILY COURT','South Shields County Court',NULL),
('517400','953','SUNDERLAND COUNTY, FAMILY, MAGISTRATES AND TRIBUNAL HEARINGS','Sunderland County Court',NULL),
('195537','954','TEESSIDE COMBINED COURT CENTRE','Teesside Combined Court - Crown',NULL),
('195537','955','TEESSIDE COMBINED COURT CENTRE','Teesside Combined Court - County',NULL),
('852649','956','WAKEFIELD CIVIL AND FAMILY JUSTICE CENTRE','Wakefield County Court',NULL),
('107581','957','YORK COUNTY COURT AND FAMILY COURT','York County Court',NULL),
('67542','958','YORK CROWN COURT','York Crown Court',NULL),
('761518','961','BARROW-IN-FURNESS COUNTY COURT AND FAMILY COURT','Barrow in Furness County Court',NULL),
('444097','962','BIRKENHEAD COUNTY COURT AND FAMILY COURT','Birkenhead County Court',NULL),
('150431','963','BLACKBURN COUNTY COURT AND FAMILY COURT','Blackburn County Court',NULL),
('336348','964','BLACKPOOL MAGISTRATES COURT','Blackpool County Court',NULL),
('447533','965','BOLTON COMBINED COURT','Bolton Combined Court - Crown',NULL),
('448747','967','BURNLEY COMBINED COURT CENTRE','Burnley Combined Court - Crown',NULL),
('448747','968','BURNLEY COMBINED COURT CENTRE','Burnley Combined Court - County',NULL),
('45106','970','CARLISLE COMBINED COURT','Carlisle Combined Court - County',NULL),
('45106','971','CARLISLE COMBINED COURT','Carlisle Combined Court - Crown',NULL),
('226511','972','CHESTER CIVIL AND FAMILY JUSTICE CENTRE','Chester County Court',NULL),
('566296','973','CREWE (SOUTH CHESHIRE) MAGISTRATES COURT','Crewe County Court',NULL),
('353615','975','LANCASTER MAGISTRATES COURT','Lancaster County Court',NULL),
('345663','976','LIVERPOOL CIVIL AND FAMILY COURT','Liverpool County Court',NULL),
('701411','978','MANCHESTER COUNTY AND FAMILY COURT','Manchester County Court',NULL),
('232580','980','PRESTON COMBINED COURT CENTRE','Preston Combined Court - County',NULL),
('563906','982','ST HELENS COUNTY COURT AND FAMILY COURT','St Helens County Court',NULL),
('560788','983','STOCKPORT MAGISTRATES COURT AND FAMILY COURT','Stockport County Court',NULL),
('209396','987','WEST CUMBRIA COURTHOUSE','West Cumbria County Court',NULL),
('245068','988','WIGAN AND LEIGH MAGISTRATES COURT','Wigan County Court',NULL),
('468040','989','CHESTER CROWN COURT','Chester Crown Court',NULL),
('448077','990','LIVERPOOL CROWN COURT','Liverpool Crown Court',NULL),
('144641','991','MANCHESTER CROWN COURT (CROWN SQUARE)','Manchester Crown Square Crown Court',NULL),
('326944','992','MANCHESTER CROWN COURT (MINSHULL ST)','Manchester Minshull Street Crown Court',NULL),
('409795','993','WARRINGTON COMBINED COURT','Warrington Crown Court',NULL),
('827534','994','ABERYSTWYTH JUSTICE CENTRE','Aberystwyth Justice Centre - County',NULL),
('304576','995','BLACKWOOD CIVIL AND FAMILY COURT','Blackwood Civil and Family Centre - County',NULL),
('304576','996','BLACKWOOD CIVIL AND FAMILY COURT','Blackwood Civil and Family Centre - Family',NULL),
('366572','999','CAERNARFON  JUSTICE CENTRE','Caernarfon County Court',NULL),
('366572','1000','CAERNARFON  JUSTICE CENTRE','Caernarfon Criminal Justice Centre - Crown',NULL),
('234850','1001','CARDIFF CIVIL AND FAMILY JUSTICE CENTRE','Cardiff Civil Justice Centre - County',NULL),
('234850','1002','CARDIFF CIVIL AND FAMILY JUSTICE CENTRE','Cardiff Civil Justice Centre - Family',NULL),
('302630','1003','CARDIFF CROWN COURT','Cardiff Crown Court',NULL),
('101959','1004','CARMARTHEN COUNTY COURT AND FAMILY COURT','Carmarthen County Court',NULL),
('101959','1005','CARMARTHEN COUNTY COURT AND FAMILY COURT','Carmarthen Law Courts - Family',NULL),
('700596','1008','HAVERFORDWEST COUNTY COURT AND FAMILY COURT','Haverfordwest County Court',NULL),
('860090','1009','LLANDRINDOD WELLS MAGISTRATES AND FAMILY COURT','Llandrindod Wells Justice Centre - Family',NULL),
('390932','1010','LLANELLI  JUSTICE CENTRE','Llanelli County Court',NULL),
('448345','1012','MERTHYR TYDFIL COMBINED COURT CENTRE','Merthyr Tydfil Combined Court - Crown',NULL),
('448345','1013','MERTHYR TYDFIL COMBINED COURT CENTRE','Merthyr Tydfil Combined Court - County',NULL),
('211138','1014','MOLD JUSTICE CENTRE','Mold Law Courts - Crown',NULL),
('211138','1015','MOLD JUSTICE CENTRE','Mold Law Courts - County',NULL),
('846055','1016','PORT TALBOT JUSTICE CENTRE','Neath & Port Talbot County Court',NULL),
('217250','1017','NEWPORT (SOUTH WALES) COUNTY COURT AND FAMILY COURT','Newport Civil and Family Court - County',NULL),
('217250','1018','NEWPORT (SOUTH WALES) COUNTY COURT AND FAMILY COURT','Newport Civil and Family Court - Family',NULL),
('200518','1019','NEWPORT (SOUTH WALES) CROWN COURT','Newport Crown Court',NULL),
('232298','1020','PONTYPRIDD COUNTY COURT AND FAMILY COURT','Pontypridd County Court',NULL),
('846055','1021','PORT TALBOT JUSTICE CENTRE','Port Talbot Justice Centre - Family',NULL),
('234946','1023','SWANSEA CIVIL AND FAMILY JUSTICE CENTRE','Swansea Civil Justice Centre - County',NULL),
('234946','1024','SWANSEA CIVIL AND FAMILY JUSTICE CENTRE','Swansea Civil Justice Centre - Family',NULL),
('279152','1025','SWANSEA CROWN COURT','Swansea Crown Court',NULL),
('103147','1026','WELSHPOOL MAGISTRATES COURT','Welshpool County Court',NULL),
('637145','1027','WREXHAM LAW COURTS','Wrexham Law Courts - County',NULL),
('416695','1060','HIGHBURY CORNER MAGISTRATES COURT','Highbury Corner Magistrates Court',NULL),
('839746','1061','WESTMINSTER MAGISTRATES COURT','Westminster Magistrates Court',NULL),
('549957','1063','WIMBLEDON MAGISTRATES COURT','Wimbledon Magistrates Court',NULL),
('664444','1065','THAMES MAGISTRATES COURT','Thames Magistrates Court',NULL),
('745389','1066','HENDON MAGISTRATES COURT','Hendon Magistrates Court',NULL),
('514973','1067','STRATFORD MAGISTRATES COURT','Stratford Magistrates Court',NULL),
('597501','1068','EALING MAGISTRATES COURT','Ealing Magistrates Court',NULL),
('784131','1069','BROMLEY MAGISTRATES COURT','Bromley Magistrates Court',NULL),
('747662','1070','CROYDON MAGISTRATES COURT','Croydon Magistrates Court',NULL),
('490237','1451','POOLE MAGISTRATES COURT','Poole Magistrates Court',NULL),
('536548','1071','LAVENDER HILL MAGISTRATES COURT (FORMERLY SOUTH WESTERN MAGISTRATES COURT)','Lavendar Hill Magistrates Court',NULL),
('218723','1073','Barkingside Magistrates'' Court','Redbridge Magistrates Court',NULL),
('264828','1074','UXBRIDGE MAGISTRATES COURT','Uxbridge Magistrates Court',NULL),
('618632','1075','NOTTINGHAM MAGISTRATES COURT','Nottingham Magistrates Court',NULL),
('703200','1076','WORCESTER MAGISTRATES COURT','Worcester Magistrates Court',NULL),
('784730','1077','BIRMINGHAM MAGISTRATES COURT','Birmingham Magistrates Court',NULL),
('417439','1078','LEICESTER MAGISTRATES COURT','Leicester Magistrates Court',NULL),
('652852','1079','CHESTERFIELD MAGISTRATES','Chesterfield Magistrates Court',NULL),
('370964','1080','NORTH STAFFORDSHIRE JUSTICE CENTRE','North Staffordshire Justice Centre - Magistrates',NULL),
('484482','1081','DERBY MAGISTRATES','Derby Magistrates Court',NULL),
('590621','1082','WOLVERHAMPTON MAGISTRATES COURT','Wolverhampton Magistrates Court',NULL),
('443257','1083','NORTH TYNESIDE MAGISTRATES COURT','North Tyneside Magistrates Court',NULL),
('580554','1084','BRADFORD  AND KEIGHLEY MAGISTRATES COURT AND FAMILY COURT','Bradford Magistrates Court',NULL),
('517400','1085','SUNDERLAND COUNTY, FAMILY, MAGISTRATES AND TRIBUNAL HEARINGS','Sunderland Magistrates Court',NULL),
('641199','1086','GRIMSBY MAGISTRATES COURT AND FAMILY COURT','Grimsby Magistrates Court',NULL),
('720624','1087','SHEFFIELD MAGISTRATES COURT','Sheffield Magistrates Court',NULL),
('320113','1088','KIRKLEES (HUDDERSFIELD) MAGISTRATES COURT AND FAMILY COURT ','Kirklees Magistrates Court',NULL),
('574546','1089','BARNSLEY LAW COURTS','Barnsley Magistrates Court',NULL),
('449358','1090','TEESSIDE MAGISTRATES COURT','Teeside Magistrates Court',NULL),
('569737','1091','LEEDS MAGISTRATES COURT AND FAMILY COURT','Leeds Magistrates Court',NULL),
('362420','1093','HULL MAGISTRATES COURT','Hull Magistrates Court',NULL),
('360566','1094','WIRRAL MAGISTRATES COURT','Wirral Magistrates Court',NULL),
('336348','1095','BLACKPOOL MAGISTRATES COURT','Blackpool Magistrates Court',NULL),
('783803','1096','MANCHESTER MAGISTRATES COURT','Manchester Magistrates Court',NULL),
('243126','1097','CARLISLE MAGISTRATES COURT','Carlisle (Cumbria) Magistrates Court',NULL),
('345663','1098','LIVERPOOL CIVIL AND FAMILY COURT','Liverpool Magistrates Court ',NULL),
('215156','1099','BLACKBURN MAGISTRATES COURT','Blackburn Magistrates Court',NULL),
('409795','1101','WARRINGTON COMBINED COURT','Warrington Magistrates Court',NULL),
('568484','1102','GUILDFORD MAGISTRATES COURT AND FAMILY COURT','Guildford Magistrates Court',NULL),
('659591','1103','MARGATE MAGISTRATES COURT','Margate Magistrates Court',NULL),
('497356','1104','MILTON KEYNES MAGISTRATES COURT AND FAMILY COURT','Milton Keynes Magistrates Court',NULL),
('287515','1105','IPSWICH MAGISTRATES COURT','Ipswich Magistrates Court',NULL),
('624810','1106','CHELMSFORD MAGISTRATES COURT AND FAMILY COURT','Chelmsford Magistrates Court',NULL),
('245287','1107','READING MAGISTRATES COURT AND FAMILY COURT','Reading Magistrates Court',NULL),
('252292','1108','LUTON AND SOUTH BEDFORDSHIRE MAGISTRATES COURT AND FAMILY COURT','Luton Magistrates Court',NULL),
('732661','1109','OXFORD AND SOUTHERN OXFORDSHIRE MAGISTRATES COURT','Oxford Magistrates Court',NULL),
('625697','1110','ST ALBANS MAGISTRATES COURT ','St Albans Magistrates Court',NULL),
('583034','1111','PETERBOROUGH MAGISTRATES COURT','Peterborough Magistrates Court',NULL),
('417418','1112','BRIGHTON MAGISTRATES COURT','Brighton Magistrates Court',NULL),
('777942','1113','NORWICH MAGISTRATES COURT AND FAMILY COURT','Norwich Magistrates Court',NULL),
('224403','1114','SLOUGH COUNTY COURT AND FAMILY COURT','Slough Magistrates Court',NULL),
('379247','1115','PORTSMOUTH MAGISTRATES COURT','Portsmouth Magistrates Court',NULL),
('314074','1117','SWINDON MAGISTRATES COURT','Swindon Magistrates Court',NULL),
('450049','1118','ALDERSHOT JUSTICE CENTRE','Aldershot Magistrates Court',NULL),
('764728','1119','PLYMOUTH MAGISTRATES COURT','Plymouth Magistrates Court',NULL),
('781155','1120','BRISTOL MAGISTRATES COURT','Bristol Magistrates Court',NULL),
('330480','1121','WEST HAMPSHIRE MAGISTRATES COURT','Southampton Magistrates Court',NULL),
('506742','1123','TAUNTON MAGISTRATES COURT, TRIBUNALS AND FAMILY HEARING CENTRE','Taunton Magistrates Court',NULL),
('779109','1124','CARDIFF  MAGISTRATES COURT','Cardiff Magistrates Court',NULL),
('211138','1125','MOLD JUSTICE CENTRE','Mold Magistrates Court',NULL),
('324413','1126','NEWPORT (SOUTH WALES) MAGISTRATES COURT','Newport Magistrates Court',NULL),
('296111','1127','CWMBRAN MAGISTRATES COURT','Cwmbran Magistrates Court',NULL),
('20262','1147','ROYAL COURTS OF JUSTICE','Royal Courts of Justice - Senior Costs Office',NULL),
('427519','1156','GATESHEAD MAGISTRATES COURT AND FAMILY COURT','Gateshead Magistrates Court',NULL),
('326813','1163','WALSALL MAGISTRATES COURT','Walsall Magistrate''s Court',NULL),
('602948','1164','NORTHAMPTON MAGISTRATES COURT','Northampton Magistrates Court ',NULL),
('534157','1165','LINCOLN MAGISTRATES COURT','Lincoln Magistrates Court',NULL),
('330480','1166','WEST HAMPSHIRE MAGISTRATES COURT','West Hampshire Magistrates Court ',NULL),
('541183','1167','WILLESDEN MAGISTRATES COURT','Willesden Magistrates Court ',NULL),
('787030','1168','COVENTRY MAGISTRATES COURT','Coventry Magistrates Court',NULL),
('361595','1169','LLANDUDNO MAGISTRATES COURT','Llandudno Magistrates Court ',NULL),
('218723','1170','BARKINGSIDE  MAGISTRATES COURT','Barkingside Magistrates Court',NULL),
('478126','1171','GREAT GRIMSBY COMBINED COURT CENTRE','Grimsby County Court',NULL),
('371016','1172','OXFORD COMBINED COURT CENTRE','Oxford Combined Court Centre',NULL),
('819890','1173','BRISTOL CIVIL AND FAMILY JUSTICE CENTRE','Bristol Civil and Family Justice Centre',NULL),
('379656','1192','PRESTATYN JUSTICE CENTRE','Prestatyn Civil and Family Justice Centre',NULL),
('640119','1194','DONCASTER JUSTICE CENTRE NORTH','Doncaster Magistrates Court',NULL),
('711798','1437','CHELTENHAM MAGISTRATES COURT','Cheltenham Magistrates Court',NULL),
('270253','1445','NEWTON ABBOT MAGISTRATES COURT','Newton Abbot Magistrates Court',NULL),
('771467','1446','MEDWAY MAGISTRATES COURT AND FAMILY COURT','Medway Magistrates Court',NULL),
('736719','916','LEAMINGTON SPA MAGISTRATES'' COURT','Warwick Combined Court - County',NULL),
('232580','981','PRESTON COMBINED COURT CENTRE','Preston Combined Court - Crown',NULL),
('415903','1191','LEYLAND FAMILY COURT','Leyland Family Hearing Centre',NULL),
('450049','1447','ALDERSHOT JUSTICE CENTRE','Aldershot Justice Centre - Crown',NULL),
('450049','1448','ALDERSHOT JUSTICE CENTRE','Aldershot Justice Centre - County',NULL),
('640119','1449','DONCASTER JUSTICE CENTRE NORTH','Doncaster Justice Centre North',NULL),
('45900','1450','DONCASTER JUSTICE CENTRE SOUTH','Doncaster Justice Centre South',NULL),
('366796','1452','NEWCASTLE CIVIL & FAMILY COURTS AND TRIBUNALS CENTRE','Newcastle Civil & Family Courts & Tribunals Centre',NULL);
COMMIT;