DROP TABLE judicial_service_code_mapping;

CREATE TABLE judicial_service_code_mapping(
    service_id bigint NOT NULL,
    ticket_code varchar(16) NOT NULL,
    service_code varchar(64),
    service_description varchar(512),
    CONSTRAINT service_id PRIMARY KEY (service_id)
);

INSERT INTO judicial_service_code_mapping (service_id,ticket_code,service_code,service_description)
VALUES ('1','368','BBA3','Social Security and Child Support'),
('2','364','BBA3','Social Security and Child Support'),
('3','362','BBA3','Social Security and Child Support'),
('4','365','BBA3','Social Security and Child Support'),
('5','366','BBA3','Social Security and Child Support'),
('6','367','BBA3','Social Security and Child Support'),
('7','369','BBA3','Social Security and Child Support'),
('8','290',' ',''),
('9','291',' ',''),
('10','387',' ',''),
('11','318','BGA1','Agricultural Land and Drainage'),
('12','402','ABA2','Financial Remedy'),
('13','303',' ',''),
('14','320',' ',''),
('15','304',' ',''),
('16','321','BCA1','Care Standards'),
('17','305',' ',''),
('18','292',' ',''),
('19','293',' ',''),
('20','322','BAA2','Charity'),
('21','363','BBA3','Social Security and Child Support'),
('22','407',' ',''),
('23','294','AAA1','Civil Enforcement'),
('24','294','AAA2','Insolvency'),
('25','294','AAA3','Mortgage and Landlord Possession Claims'),
('26','294','AAA4','Non-money Claims'),
('27','294','AAA5','Return of Goods Claims'),
('28','294','AAA6','Specified Money Claims'),
('29','294','AAA7','Damages'),
('30','295',' ',''),
('31','325',' ',''),
('32','326','BAA4','Consumer Credit'),
('33','307',' ',''),
('34','313','ABA7','Court of Protections'),
('35','306',' ',''),
('36','328','BBA2','Criminal Injuries Compensation'),
('37','405','ABA3','Family Public Law'),
('38','405','ABA4','Adoption'),
('39','405','ABA5','Family Private Law'),
('40','405','ABA8','REMO'),
('41','331','BAA5','Environment'),
('42','332','BAA6','Estate Agents'),
('43','308',' ',''),
('44','389','ABA3','Family Public Law'),
('45','389','ABA4','Adoption'),
('46','389','ABA5','Family Private Law'),
('47','389','ABA8','REMO'),
('48','410','ABA2','Financial Remedy'),
('49','409',' ',''),
('50','314','ABA2','Financial Remedy'),
('51','392',' ',''),
('52','374',' ',''),
('53','373','BFA1','Immigration and Asylum Appeals'),
('54','375',' ',''),
('55','376','BBA3','Social Security and Child Support'),
('56','377',' ',''),
('57','378','BEA1','War Pensions Appeals'),
('58','395',' ',''),
('59','334','BAA8','Gambling Appeals'),
('60','336','BAB1','Information Rights'),
('61','337',' ',''),
('62','340','BGA2','Land Registration'),
('63','341','BAB2','Local Government Standards'),
('64','406',' ',''),
('65','412',' ',''),
('66','342','BCA2','Mental Health'),
('67','343','BCA2','Mental Health'),
('68','298',' ',''),
('69','309',' ',''),
('70','346',' ',''),
('71','404',' ',''),
('72','379','BHA1','Employment Claims'),
('73','381',' ',''),
('74','382',' ',''),
('75','383',' ',''),
('76','384','BBA1','Asylum Support'),
('77','299',' ',''),
('78','347',' ',''),
('79','350',' ',''),
('80','394',' ',''),
('81','349','BCA3','Primary Health Lists'),
('82','315','ABA5','Family Private Law'),
('83','316','ABA3','Family Public Law'),
('84','351',' ',''),
('85','352',' ',''),
('86','353','BHA3','Reserve Forces Appeal Tribunal'),
('87','354','BGA3','Residential Property'),
('88','356',' ',''),
('89','397',' ',''),
('90','400',' ',''),
('91','398',' ',''),
('92','317',' ',''),
('93','300',' ',''),
('94','396',' ',''),
('95','301',' ',''),
('96','393',' ',''),
('97','311',' ',''),
('98','312',' ',''),
('99','408',' ',''),
('100','357','BBA3','Social Security and Child Support'),
('101','358',' ',''),
('102','411',' ',''),
('103','302',' ',''),
('104','310',' ',''),
('105','359',' ',''),
('106','360','BAB3','Transport'),
('107','370',' ',''),
('108','371',' ',''),
('109','372','BAA9','Immigration Services'),
('110','385',' ',''),
('111','386','BDA2','Tax Appeals'),
('112','289',' ',''),
('113','388',' ','');



CREATE TABLE judicial_ticket_code_mapping(
    ticket_code varchar(16) NOT NULL,
    jurisdiction varchar(256) NOT NULL,
    lower_level varchar(256) NOT NULL
);

INSERT INTO judicial_ticket_code_mapping (ticket_code,jurisdiction,lower_level)
VALUES ('368','Authorisation Tribunals','00 - Interlocutory'),
('364','Authorisation Tribunals','01 - Social Security'),
('362','Authorisation Tribunals','02 - Child Support'),
('365','Authorisation Tribunals','03 - Disability Living Allowance'),
('366','Authorisation Tribunals','04 - Incapacity Benefit Employment Support'),
('367','Authorisation Tribunals','05 - Industrial Injuries'),
('369','Authorisation Tribunals','07 - Vaccine Damage'),
('290','Authorisation Civil','Administrative Court'),
('291','Authorisation Civil','Admiralty - QBD'),
('387','Authorisation Magistrate','Adult Court'),
('318','Authorisation Tribunals','Agricultural Land and Drainage'),
('402','Authorisation Family','Ancillary Relief Appeals'),
('303','Authorisation Crime','Appeals in Crown Court'),
('320','Authorisation Tribunals','Asylum Support'),
('304','Authorisation Crime','Attempted Murder'),
('321','Authorisation Tribunals','Care Standards'),
('305','Authorisation Crime','Central Criminal Court'),
('292','Authorisation Civil','Chancery'),
('293','Authorisation Civil','Chancery Business in the County Court'),
('322','Authorisation Tribunals','Charity'),
('363','Authorisation Tribunals','Child Support 02'),
('407','Authorisation Civil','Circuit Commercial Court'),
('294','Authorisation Civil','Civil Authorisation'),
('295','Authorisation Civil','Commercial'),
('325','Authorisation Tribunals','Competition Appeal Tribunal'),
('326','Authorisation Tribunals','Consumer Credit'),
('307','Authorisation Crime','Court of Appeal Criminal Division'),
('313','Authorisation Family','Court of Protection'),
('306','Authorisation Crime','Criminal Authorisation'),
('328','Authorisation Tribunals','Criminal Injuries Compensations'),
('405','Authorisation Magistrate','Direct Recruitment to Family'),
('331','Authorisation Tribunals','Environment'),
('332','Authorisation Tribunals','Estate Agents'),
('308','Authorisation Crime','Extradition'),
('389','Authorisation Magistrate','Family Court'),
('410','Authorisation Family','Financial Remedy'),
('409','Authorisation Civil','Financial Remedy '),
('314','Authorisation Family','Financial Remedy Appeals'),
('392','Authorisation Tribunals','First Tier - General Regulatory'),
('374','Authorisation Tribunals','First Tier - Health, Education and Social Care'),
('373','Authorisation Tribunals','First Tier - Immigration and Asylum'),
('375','Authorisation Tribunals','First Tier - Property'),
('376','Authorisation Tribunals','First Tier - Social Entitlement'),
('377','Authorisation Tribunals','First Tier - Tax'),
('378','Authorisation Tribunals','First Tier - War Pensions and Armed Forces Compensation'),
('395','Authorisation Civil','Freezing Orders in the County Court'),
('334','Authorisation Tribunals','Gambling'),
('336','Authorisation Tribunals','Information Rights'),
('337','Authorisation Tribunals','Judicial Review - England and Wales'),
('340','Authorisation Tribunals','Land Registration'),
('341','Authorisation Tribunals','Local Government Standards - England'),
('406','Authorisation Civil','London Circuit Commercial Court'),
('412','Authorisation Civil','Media and Communications List'),
('342','Authorisation Tribunals','Mental Health'),
('343','Authorisation Tribunals','Mental Health Tribunal Wales'),
('298','Authorisation Civil','Mercantile - QBD'),
('309','Authorisation Crime','Murder'),
('346','Authorisation Tribunals','National Security'),
('404','Authorisation Civil','Ordinary Planning'),
('379','Authorisation Tribunals','Others - Employment Appeals Tribunal'),
('381','Authorisation Tribunals','Others - Gender Recognition Panel'),
('382','Authorisation Tribunals','Others - Pathogens Access Appeals Commission'),
('383','Authorisation Tribunals','Others - Proscribed Organisations Appeal Commission'),
('384','Authorisation Tribunals','Others - Special Immigration Appeals Commission'),
('299','Authorisation Civil','Patents'),
('347','Authorisation Tribunals','Pensions Regulations'),
('350','Authorisation Tribunals','Police Appeal Tribunal'),
('394','Authorisation Crime','Pool of Judges'),
('349','Authorisation Tribunals','Primary Health List'),
('315','Authorisation Family','Private Law'),
('316','Authorisation Family','Public Law'),
('351','Authorisation Tribunals','Race Panel'),
('352','Authorisation Tribunals','Reinstatement Committee'),
('353','Authorisation Tribunals','Reserve Forces'),
('354','Authorisation Tribunals','Residential Property'),
('356','Authorisation Tribunals','Restricted Patients Panel'),
('397','Authorisation Civil','S9(4), Appointment - Chancery'),
('400','Authorisation Family','S9(4), Appointment - Family'),
('398','Authorisation Civil','S9(4), Appointment - Queens Bench'),
('317','Authorisation Family','Section 9-1 Family'),
('300','Authorisation Civil','Section 9(1), Chancery'),
('396','Authorisation Civil','Section 9(1), IPEC'),
('301','Authorisation Civil','Section 9(1), Queens Bench'),
('393','Authorisation Civil','Section 9(1), Queens Bench - Admin ONLY'),
('311','Authorisation Crime','Serious Sexual Offences'),
('312','Authorisation Crime','Serious Sexual Offences - Youth Court'),
('408','Authorisation Civil','Significant Planning'),
('357','Authorisation Tribunals','Social Security and Child Support'),
('358','Authorisation Tribunals','Special Educational Needs and Disability'),
('411','Authorisation Civil','Super Planning'),
('302','Authorisation Civil','Technology and Construction Court'),
('310','Authorisation Crime','Terrorism'),
('359','Authorisation Tribunals','Trade Marks Tribunal'),
('360','Authorisation Tribunals','Transport'),
('370','Unknown','Unknown'),
('371','Authorisation Tribunals','Upper - Administrative Appeals'),
('372','Authorisation Tribunals','Upper - Immigration and Asylum'),
('385','Authorisation Tribunals','Upper - Lands'),
('386','Authorisation Tribunals','Upper - Tax and Chancery'),
('289','Languages','Welsh'),
('388','Authorisation Magistrate','Youth Court');

